[package]
name = "ride-editor"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"

[lib]
name = "ride_editor"
path = "crates/lib.rs"

[[bin]]
name = "ride-editor"
path = "crates/ride-editor/main.rs"

[[bin]]
name = "ride-fm"
path = "crates/filemngd/main.rs"
