import "fonts/SourceHanSans-VF.ttf.ttc";

export component StatusLine {
    in-out property <string> mode: "NORMAL";
    in-out property <string> file-name: "[No Name]";
    in-out property <color> mode-background: mode == "NORMAL" ? #4CAF50 : (mode == "INSERT" ? #EF5350 : #FFCA28);
    in-out property <color> mode-text-color: mode == "NORMAL" || mode == "INSERT" ? #FFFFFF : #1E1E1E;
    height: 24px;

    animate mode-background { duration: 200ms; easing: ease-in-out; }
    animate mode-text-color { duration: 200ms; easing: ease-in-out; }

    Rectangle {
        background: #3C3F41;

        HorizontalLayout {
            padding-left: 8px;
            padding-right: 8px;

            Rectangle {
                background: mode-background;
                horizontal-stretch: 0;
                width: 84px;

                HorizontalLayout {
                    padding-left: 6px;
                    padding-right: 6px;

                    Text {
                        text: mode;
                        color: mode-text-color;
                        font-family: "Source Han Sans VF";
                        font-weight: 600;
                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }
            }

            Text {
                text: file-name;
                color: #A9B7C6;
                font-family: "Source Han Sans VF";
                horizontal-stretch: 1;
                vertical-alignment: center;
            }
        }
    }
}
